// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: Propose.proto

package Propose

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puerto  string `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	NChunks int64  `protobuf:"varint,2,opt,name=NChunks,proto3" json:"NChunks,omitempty"`
}

func (x *Propuesta) Reset() {
	*x = Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta) ProtoMessage() {}

func (x *Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta.ProtoReflect.Descriptor instead.
func (*Propuesta) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{0}
}

func (x *Propuesta) GetPuerto() string {
	if x != nil {
		return x.Puerto
	}
	return ""
}

func (x *Propuesta) GetNChunks() int64 {
	if x != nil {
		return x.NChunks
	}
	return 0
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_Propose_proto protoreflect.FileDescriptor

var file_Propose_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x47, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x34, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x1a,
	0x12, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Propose_proto_rawDescOnce sync.Once
	file_Propose_proto_rawDescData = file_Propose_proto_rawDesc
)

func file_Propose_proto_rawDescGZIP() []byte {
	file_Propose_proto_rawDescOnce.Do(func() {
		file_Propose_proto_rawDescData = protoimpl.X.CompressGZIP(file_Propose_proto_rawDescData)
	})
	return file_Propose_proto_rawDescData
}

var file_Propose_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Propose_proto_goTypes = []interface{}{
	(*Propuesta)(nil), // 0: Propose.Propuesta
	(*Respuesta)(nil), // 1: Propose.Respuesta
}
var file_Propose_proto_depIdxs = []int32{
	0, // 0: Propose.ProponerService.Proponer:input_type -> Propose.Propuesta
	1, // 1: Propose.ProponerService.Proponer:output_type -> Propose.Respuesta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Propose_proto_init() }
func file_Propose_proto_init() {
	if File_Propose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Propose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Propose_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Propose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Propose_proto_goTypes,
		DependencyIndexes: file_Propose_proto_depIdxs,
		MessageInfos:      file_Propose_proto_msgTypes,
	}.Build()
	File_Propose_proto = out.File
	file_Propose_proto_rawDesc = nil
	file_Propose_proto_goTypes = nil
	file_Propose_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProponerServiceClient is the client API for ProponerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProponerServiceClient interface {
	Proponer(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Respuesta, error)
}

type proponerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProponerServiceClient(cc grpc.ClientConnInterface) ProponerServiceClient {
	return &proponerServiceClient{cc}
}

func (c *proponerServiceClient) Proponer(ctx context.Context, in *Propuesta, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Propose.ProponerService/Proponer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProponerServiceServer is the server API for ProponerService service.
type ProponerServiceServer interface {
	Proponer(context.Context, *Propuesta) (*Respuesta, error)
}

// UnimplementedProponerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProponerServiceServer struct {
}

func (*UnimplementedProponerServiceServer) Proponer(context.Context, *Propuesta) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proponer not implemented")
}

func RegisterProponerServiceServer(s *grpc.Server, srv ProponerServiceServer) {
	s.RegisterService(&_ProponerService_serviceDesc, srv)
}

func _ProponerService_Proponer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Propuesta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProponerServiceServer).Proponer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Propose.ProponerService/Proponer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProponerServiceServer).Proponer(ctx, req.(*Propuesta))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProponerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ProponerService",
	HandlerType: (*ProponerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proponer",
			Handler:    _ProponerService_Proponer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Propose.proto",
}
