// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Propose.proto

package Propose

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Propuesta struct {
	Vm1                  string   `protobuf:"bytes,1,opt,name=Vm1,proto3" json:"Vm1,omitempty"`
	Vm2                  string   `protobuf:"bytes,2,opt,name=Vm2,proto3" json:"Vm2,omitempty"`
	Vm3                  string   `protobuf:"bytes,3,opt,name=Vm3,proto3" json:"Vm3,omitempty"`
	Cant1                int64    `protobuf:"varint,4,opt,name=Cant1,proto3" json:"Cant1,omitempty"`
	Cant2                int64    `protobuf:"varint,5,opt,name=Cant2,proto3" json:"Cant2,omitempty"`
	Cant3                int64    `protobuf:"varint,6,opt,name=Cant3,proto3" json:"Cant3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Propuesta) Reset()         { *m = Propuesta{} }
func (m *Propuesta) String() string { return proto.CompactTextString(m) }
func (*Propuesta) ProtoMessage()    {}
func (*Propuesta) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{0}
}

func (m *Propuesta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propuesta.Unmarshal(m, b)
}
func (m *Propuesta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propuesta.Marshal(b, m, deterministic)
}
func (m *Propuesta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propuesta.Merge(m, src)
}
func (m *Propuesta) XXX_Size() int {
	return xxx_messageInfo_Propuesta.Size(m)
}
func (m *Propuesta) XXX_DiscardUnknown() {
	xxx_messageInfo_Propuesta.DiscardUnknown(m)
}

var xxx_messageInfo_Propuesta proto.InternalMessageInfo

func (m *Propuesta) GetVm1() string {
	if m != nil {
		return m.Vm1
	}
	return ""
}

func (m *Propuesta) GetVm2() string {
	if m != nil {
		return m.Vm2
	}
	return ""
}

func (m *Propuesta) GetVm3() string {
	if m != nil {
		return m.Vm3
	}
	return ""
}

func (m *Propuesta) GetCant1() int64 {
	if m != nil {
		return m.Cant1
	}
	return 0
}

func (m *Propuesta) GetCant2() int64 {
	if m != nil {
		return m.Cant2
	}
	return 0
}

func (m *Propuesta) GetCant3() int64 {
	if m != nil {
		return m.Cant3
	}
	return 0
}

type InfoMaquina struct {
	Puerto               string     `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	Propuesta            *Propuesta `protobuf:"bytes,2,opt,name=Propuesta,proto3" json:"Propuesta,omitempty"`
	Nchunks              int64      `protobuf:"varint,3,opt,name=Nchunks,proto3" json:"Nchunks,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InfoMaquina) Reset()         { *m = InfoMaquina{} }
func (m *InfoMaquina) String() string { return proto.CompactTextString(m) }
func (*InfoMaquina) ProtoMessage()    {}
func (*InfoMaquina) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{1}
}

func (m *InfoMaquina) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMaquina.Unmarshal(m, b)
}
func (m *InfoMaquina) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMaquina.Marshal(b, m, deterministic)
}
func (m *InfoMaquina) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMaquina.Merge(m, src)
}
func (m *InfoMaquina) XXX_Size() int {
	return xxx_messageInfo_InfoMaquina.Size(m)
}
func (m *InfoMaquina) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMaquina.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMaquina proto.InternalMessageInfo

func (m *InfoMaquina) GetPuerto() string {
	if m != nil {
		return m.Puerto
	}
	return ""
}

func (m *InfoMaquina) GetPropuesta() *Propuesta {
	if m != nil {
		return m.Propuesta
	}
	return nil
}

func (m *InfoMaquina) GetNchunks() int64 {
	if m != nil {
		return m.Nchunks
	}
	return 0
}

func (m *InfoMaquina) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Libro struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Libro) Reset()         { *m = Libro{} }
func (m *Libro) String() string { return proto.CompactTextString(m) }
func (*Libro) ProtoMessage()    {}
func (*Libro) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{2}
}

func (m *Libro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Libro.Unmarshal(m, b)
}
func (m *Libro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Libro.Marshal(b, m, deterministic)
}
func (m *Libro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Libro.Merge(m, src)
}
func (m *Libro) XXX_Size() int {
	return xxx_messageInfo_Libro.Size(m)
}
func (m *Libro) XXX_DiscardUnknown() {
	xxx_messageInfo_Libro.DiscardUnknown(m)
}

var xxx_messageInfo_Libro proto.InternalMessageInfo

func (m *Libro) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReceptStatus struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceptStatus) Reset()         { *m = ReceptStatus{} }
func (m *ReceptStatus) String() string { return proto.CompactTextString(m) }
func (*ReceptStatus) ProtoMessage()    {}
func (*ReceptStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{3}
}

func (m *ReceptStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceptStatus.Unmarshal(m, b)
}
func (m *ReceptStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceptStatus.Marshal(b, m, deterministic)
}
func (m *ReceptStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceptStatus.Merge(m, src)
}
func (m *ReceptStatus) XXX_Size() int {
	return xxx_messageInfo_ReceptStatus.Size(m)
}
func (m *ReceptStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceptStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReceptStatus proto.InternalMessageInfo

func (m *ReceptStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type InfoChunk struct {
	Puerto               string   `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	Part                 string   `protobuf:"bytes,2,opt,name=Part,proto3" json:"Part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoChunk) Reset()         { *m = InfoChunk{} }
func (m *InfoChunk) String() string { return proto.CompactTextString(m) }
func (*InfoChunk) ProtoMessage()    {}
func (*InfoChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{4}
}

func (m *InfoChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoChunk.Unmarshal(m, b)
}
func (m *InfoChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoChunk.Marshal(b, m, deterministic)
}
func (m *InfoChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoChunk.Merge(m, src)
}
func (m *InfoChunk) XXX_Size() int {
	return xxx_messageInfo_InfoChunk.Size(m)
}
func (m *InfoChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoChunk.DiscardUnknown(m)
}

var xxx_messageInfo_InfoChunk proto.InternalMessageInfo

func (m *InfoChunk) GetPuerto() string {
	if m != nil {
		return m.Puerto
	}
	return ""
}

func (m *InfoChunk) GetPart() string {
	if m != nil {
		return m.Part
	}
	return ""
}

func init() {
	proto.RegisterType((*Propuesta)(nil), "Propose.Propuesta")
	proto.RegisterType((*InfoMaquina)(nil), "Propose.InfoMaquina")
	proto.RegisterType((*Libro)(nil), "Propose.Libro")
	proto.RegisterType((*ReceptStatus)(nil), "Propose.ReceptStatus")
	proto.RegisterType((*InfoChunk)(nil), "Propose.InfoChunk")
}

func init() { proto.RegisterFile("Propose.proto", fileDescriptor_58dd9776f9ae8f06) }

var fileDescriptor_58dd9776f9ae8f06 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xd9, 0x7f, 0x30, 0xfe, 0x3b, 0x80, 0x9a, 0x23, 0x9a, 0x06, 0x6f, 0xc8, 0xae, 0xb8,
	0x22, 0xd0, 0x25, 0xfa, 0x00, 0x78, 0x43, 0x02, 0x84, 0x8c, 0xc4, 0xfb, 0x42, 0xaa, 0x2e, 0x86,
	0x15, 0xdb, 0xce, 0x17, 0x30, 0xbe, 0xb7, 0x59, 0xb7, 0x96, 0xc6, 0xe8, 0xdd, 0x39, 0xbf, 0xb3,
	0x73, 0xf6, 0x7d, 0x5f, 0x0a, 0x83, 0xad, 0x14, 0x27, 0xa1, 0xf8, 0xf4, 0x24, 0x85, 0x16, 0xd8,
	0x6d, 0xda, 0xe4, 0x33, 0x80, 0xb8, 0xaa, 0x4b, 0xae, 0x34, 0xc3, 0x2b, 0x08, 0x9f, 0x8e, 0x73,
	0x12, 0x8c, 0x83, 0x49, 0x9c, 0x55, 0x65, 0x4d, 0x28, 0xf9, 0x67, 0x09, 0xad, 0x49, 0x4a, 0x42,
	0x4b, 0x52, 0x1c, 0x42, 0x67, 0xc1, 0x0a, 0x3d, 0x27, 0xed, 0x71, 0x30, 0x09, 0xb3, 0xba, 0xb1,
	0x94, 0x92, 0xce, 0x99, 0x52, 0x4b, 0x53, 0x12, 0x9d, 0x69, 0x9a, 0x7c, 0x05, 0xd0, 0x5b, 0x16,
	0xcf, 0x62, 0xcd, 0xde, 0xcb, 0xbc, 0x60, 0x78, 0x0b, 0xd1, 0xb6, 0xe4, 0x52, 0x8b, 0x46, 0x4a,
	0xd3, 0xe1, 0xcc, 0x13, 0x6b, 0x34, 0xf5, 0x28, 0x4e, 0xad, 0x33, 0x37, 0xc9, 0x3c, 0x47, 0x04,
	0xba, 0x9b, 0xc3, 0x6b, 0x59, 0xbc, 0x29, 0xa3, 0x38, 0xcc, 0x6c, 0x8b, 0x08, 0xed, 0x0d, 0x3b,
	0x72, 0x23, 0x3a, 0xce, 0x4c, 0x9d, 0xdc, 0x41, 0x67, 0x95, 0xef, 0xa5, 0x70, 0xc3, 0xc0, 0x1b,
	0x4e, 0xa0, 0x9f, 0xf1, 0x03, 0x3f, 0xe9, 0x9d, 0x66, 0xba, 0x54, 0xd5, 0xe9, 0x35, 0x57, 0x8a,
	0xbd, 0xd8, 0xcf, 0x6c, 0x9b, 0x3c, 0x40, 0x5c, 0xb9, 0x59, 0x54, 0x3f, 0xfa, 0xd3, 0x0b, 0x42,
	0x7b, 0xcb, 0xa4, 0x6e, 0xa2, 0x35, 0x35, 0x5d, 0xc2, 0xa5, 0x71, 0x53, 0x70, 0xb9, 0xe3, 0xf2,
	0x23, 0x3f, 0x70, 0xbc, 0x87, 0xff, 0x16, 0xe1, 0xd0, 0x79, 0xf5, 0xc2, 0x1a, 0xfd, 0x92, 0x40,
	0xd2, 0xa2, 0x8f, 0x30, 0x58, 0xe5, 0x4a, 0x33, 0x77, 0x28, 0x85, 0xa8, 0x06, 0x78, 0xe3, 0x16,
	0x7c, 0x3f, 0xa3, 0x0b, 0x87, 0x4d, 0x06, 0x49, 0x6b, 0x16, 0xd0, 0x35, 0x5c, 0xd7, 0x4b, 0xc6,
	0x8b, 0x3a, 0x8b, 0xea, 0xfb, 0x18, 0x7f, 0xac, 0x7a, 0x92, 0x5c, 0x0e, 0xd5, 0xb9, 0x7d, 0x64,
	0x5e, 0x5f, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x89, 0x80, 0xb0, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProponerServiceClient is the client API for ProponerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProponerServiceClient interface {
	Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error)
}

type proponerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProponerServiceClient(cc *grpc.ClientConn) ProponerServiceClient {
	return &proponerServiceClient{cc}
}

func (c *proponerServiceClient) Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error) {
	out := new(Propuesta)
	err := c.cc.Invoke(ctx, "/Propose.ProponerService/Proponer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProponerServiceServer is the server API for ProponerService service.
type ProponerServiceServer interface {
	Proponer(context.Context, *InfoMaquina) (*Propuesta, error)
}

// UnimplementedProponerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProponerServiceServer struct {
}

func (*UnimplementedProponerServiceServer) Proponer(ctx context.Context, req *InfoMaquina) (*Propuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proponer not implemented")
}

func RegisterProponerServiceServer(s *grpc.Server, srv ProponerServiceServer) {
	s.RegisterService(&_ProponerService_serviceDesc, srv)
}

func _ProponerService_Proponer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoMaquina)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProponerServiceServer).Proponer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Propose.ProponerService/Proponer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProponerServiceServer).Proponer(ctx, req.(*InfoMaquina))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProponerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ProponerService",
	HandlerType: (*ProponerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proponer",
			Handler:    _ProponerService_Proponer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Propose.proto",
}

// ListarServiceClient is the client API for ListarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListarServiceClient interface {
	Listar(ctx context.Context, in *ReceptStatus, opts ...grpc.CallOption) (ListarService_ListarClient, error)
}

type listarServiceClient struct {
	cc *grpc.ClientConn
}

func NewListarServiceClient(cc *grpc.ClientConn) ListarServiceClient {
	return &listarServiceClient{cc}
}

func (c *listarServiceClient) Listar(ctx context.Context, in *ReceptStatus, opts ...grpc.CallOption) (ListarService_ListarClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListarService_serviceDesc.Streams[0], "/Propose.ListarService/Listar", opts...)
	if err != nil {
		return nil, err
	}
	x := &listarServiceListarClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ListarService_ListarClient interface {
	Recv() (*Libro, error)
	grpc.ClientStream
}

type listarServiceListarClient struct {
	grpc.ClientStream
}

func (x *listarServiceListarClient) Recv() (*Libro, error) {
	m := new(Libro)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ListarServiceServer is the server API for ListarService service.
type ListarServiceServer interface {
	Listar(*ReceptStatus, ListarService_ListarServer) error
}

// UnimplementedListarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListarServiceServer struct {
}

func (*UnimplementedListarServiceServer) Listar(req *ReceptStatus, srv ListarService_ListarServer) error {
	return status.Errorf(codes.Unimplemented, "method Listar not implemented")
}

func RegisterListarServiceServer(s *grpc.Server, srv ListarServiceServer) {
	s.RegisterService(&_ListarService_serviceDesc, srv)
}

func _ListarService_Listar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceptStatus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListarServiceServer).Listar(m, &listarServiceListarServer{stream})
}

type ListarService_ListarServer interface {
	Send(*Libro) error
	grpc.ServerStream
}

type listarServiceListarServer struct {
	grpc.ServerStream
}

func (x *listarServiceListarServer) Send(m *Libro) error {
	return x.ServerStream.SendMsg(m)
}

var _ListarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ListarService",
	HandlerType: (*ListarServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listar",
			Handler:       _ListarService_Listar_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Propose.proto",
}

// ListarChunksServiceClient is the client API for ListarChunksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListarChunksServiceClient interface {
	ListarChunks(ctx context.Context, in *Libro, opts ...grpc.CallOption) (ListarChunksService_ListarChunksClient, error)
}

type listarChunksServiceClient struct {
	cc *grpc.ClientConn
}

func NewListarChunksServiceClient(cc *grpc.ClientConn) ListarChunksServiceClient {
	return &listarChunksServiceClient{cc}
}

func (c *listarChunksServiceClient) ListarChunks(ctx context.Context, in *Libro, opts ...grpc.CallOption) (ListarChunksService_ListarChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListarChunksService_serviceDesc.Streams[0], "/Propose.ListarChunksService/ListarChunks", opts...)
	if err != nil {
		return nil, err
	}
	x := &listarChunksServiceListarChunksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ListarChunksService_ListarChunksClient interface {
	Recv() (*InfoChunk, error)
	grpc.ClientStream
}

type listarChunksServiceListarChunksClient struct {
	grpc.ClientStream
}

func (x *listarChunksServiceListarChunksClient) Recv() (*InfoChunk, error) {
	m := new(InfoChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ListarChunksServiceServer is the server API for ListarChunksService service.
type ListarChunksServiceServer interface {
	ListarChunks(*Libro, ListarChunksService_ListarChunksServer) error
}

// UnimplementedListarChunksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListarChunksServiceServer struct {
}

func (*UnimplementedListarChunksServiceServer) ListarChunks(req *Libro, srv ListarChunksService_ListarChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListarChunks not implemented")
}

func RegisterListarChunksServiceServer(s *grpc.Server, srv ListarChunksServiceServer) {
	s.RegisterService(&_ListarChunksService_serviceDesc, srv)
}

func _ListarChunksService_ListarChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Libro)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListarChunksServiceServer).ListarChunks(m, &listarChunksServiceListarChunksServer{stream})
}

type ListarChunksService_ListarChunksServer interface {
	Send(*InfoChunk) error
	grpc.ServerStream
}

type listarChunksServiceListarChunksServer struct {
	grpc.ServerStream
}

func (x *listarChunksServiceListarChunksServer) Send(m *InfoChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _ListarChunksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ListarChunksService",
	HandlerType: (*ListarChunksServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListarChunks",
			Handler:       _ListarChunksService_ListarChunks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Propose.proto",
}
