// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: Notification.proto

package Notification

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Notificacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puerto1  string `protobuf:"bytes,1,opt,name=Puerto1,proto3" json:"Puerto1,omitempty"`
	Puerto2  string `protobuf:"bytes,2,opt,name=Puerto2,proto3" json:"Puerto2,omitempty"`
	Puerto3  string `protobuf:"bytes,3,opt,name=Puerto3,proto3" json:"Puerto3,omitempty"`
	NChunks1 int64  `protobuf:"varint,5,opt,name=NChunks1,proto3" json:"NChunks1,omitempty"`
	NChunks2 int64  `protobuf:"varint,6,opt,name=NChunks2,proto3" json:"NChunks2,omitempty"`
	NChunks3 int64  `protobuf:"varint,7,opt,name=NChunks3,proto3" json:"NChunks3,omitempty"`
	BookName string `protobuf:"bytes,8,opt,name=BookName,proto3" json:"BookName,omitempty"`
}

func (x *Notificacion) Reset() {
	*x = Notificacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notificacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notificacion) ProtoMessage() {}

func (x *Notificacion) ProtoReflect() protoreflect.Message {
	mi := &file_Notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notificacion.ProtoReflect.Descriptor instead.
func (*Notificacion) Descriptor() ([]byte, []int) {
	return file_Notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notificacion) GetPuerto1() string {
	if x != nil {
		return x.Puerto1
	}
	return ""
}

func (x *Notificacion) GetPuerto2() string {
	if x != nil {
		return x.Puerto2
	}
	return ""
}

func (x *Notificacion) GetPuerto3() string {
	if x != nil {
		return x.Puerto3
	}
	return ""
}

func (x *Notificacion) GetNChunks1() int64 {
	if x != nil {
		return x.NChunks1
	}
	return 0
}

func (x *Notificacion) GetNChunks2() int64 {
	if x != nil {
		return x.NChunks2
	}
	return 0
}

func (x *Notificacion) GetNChunks3() int64 {
	if x != nil {
		return x.NChunks3
	}
	return 0
}

func (x *Notificacion) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resultado string `protobuf:"bytes,1,opt,name=Resultado,proto3" json:"Resultado,omitempty"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_Notification_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetResultado() string {
	if x != nil {
		return x.Resultado
	}
	return ""
}

var File_Notification_proto protoreflect.FileDescriptor

var file_Notification_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x31, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x75, 0x65, 0x72, 0x74,
	0x6f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f,
	0x33, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x31, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x31, 0x12, 0x1a, 0x0a,
	0x08, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x4e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x33, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x33, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x29, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x1c,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x32, 0x59, 0x0a, 0x13,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x72,
	0x12, 0x1a, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x1a, 0x17, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Notification_proto_rawDescOnce sync.Once
	file_Notification_proto_rawDescData = file_Notification_proto_rawDesc
)

func file_Notification_proto_rawDescGZIP() []byte {
	file_Notification_proto_rawDescOnce.Do(func() {
		file_Notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_Notification_proto_rawDescData)
	})
	return file_Notification_proto_rawDescData
}

var file_Notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Notification_proto_goTypes = []interface{}{
	(*Notificacion)(nil), // 0: Notification.Notificacion
	(*Respuesta)(nil),    // 1: Notification.Respuesta
}
var file_Notification_proto_depIdxs = []int32{
	0, // 0: Notification.NotificationService.Notificar:input_type -> Notification.Notificacion
	1, // 1: Notification.NotificationService.Notificar:output_type -> Notification.Respuesta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Notification_proto_init() }
func file_Notification_proto_init() {
	if File_Notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notificacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Notification_proto_goTypes,
		DependencyIndexes: file_Notification_proto_depIdxs,
		MessageInfos:      file_Notification_proto_msgTypes,
	}.Build()
	File_Notification_proto = out.File
	file_Notification_proto_rawDesc = nil
	file_Notification_proto_goTypes = nil
	file_Notification_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	Notificar(ctx context.Context, in *Notificacion, opts ...grpc.CallOption) (*Respuesta, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Notificar(ctx context.Context, in *Notificacion, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Notification.NotificationService/Notificar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	Notificar(context.Context, *Notificacion) (*Respuesta, error)
}

// UnimplementedNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (*UnimplementedNotificationServiceServer) Notificar(context.Context, *Notificacion) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notificar not implemented")
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_Notificar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Notificacion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Notificar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Notification.NotificationService/Notificar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Notificar(ctx, req.(*Notificacion))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notificar",
			Handler:    _NotificationService_Notificar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Notification.proto",
}
