// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Propose.proto

package Propose

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Propuesta struct {
	Vm1                  string   `protobuf:"bytes,1,opt,name=Vm1,proto3" json:"Vm1,omitempty"`
	Vm2                  string   `protobuf:"bytes,2,opt,name=Vm2,proto3" json:"Vm2,omitempty"`
	Vm3                  string   `protobuf:"bytes,3,opt,name=Vm3,proto3" json:"Vm3,omitempty"`
	Lim1                 int64    `protobuf:"varint,4,opt,name=lim1,proto3" json:"lim1,omitempty"`
	Lim2                 int64    `protobuf:"varint,5,opt,name=lim2,proto3" json:"lim2,omitempty"`
	Lim3                 int64    `protobuf:"varint,6,opt,name=lim3,proto3" json:"lim3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Propuesta) Reset()         { *m = Propuesta{} }
func (m *Propuesta) String() string { return proto.CompactTextString(m) }
func (*Propuesta) ProtoMessage()    {}
func (*Propuesta) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{0}
}

func (m *Propuesta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propuesta.Unmarshal(m, b)
}
func (m *Propuesta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propuesta.Marshal(b, m, deterministic)
}
func (m *Propuesta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propuesta.Merge(m, src)
}
func (m *Propuesta) XXX_Size() int {
	return xxx_messageInfo_Propuesta.Size(m)
}
func (m *Propuesta) XXX_DiscardUnknown() {
	xxx_messageInfo_Propuesta.DiscardUnknown(m)
}

var xxx_messageInfo_Propuesta proto.InternalMessageInfo

func (m *Propuesta) GetVm1() string {
	if m != nil {
		return m.Vm1
	}
	return ""
}

func (m *Propuesta) GetVm2() string {
	if m != nil {
		return m.Vm2
	}
	return ""
}

func (m *Propuesta) GetVm3() string {
	if m != nil {
		return m.Vm3
	}
	return ""
}

func (m *Propuesta) GetLim1() int64 {
	if m != nil {
		return m.Lim1
	}
	return 0
}

func (m *Propuesta) GetLim2() int64 {
	if m != nil {
		return m.Lim2
	}
	return 0
}

func (m *Propuesta) GetLim3() int64 {
	if m != nil {
		return m.Lim3
	}
	return 0
}

type InfoMaquina struct {
	Puerto               string     `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	Propuesta            *Propuesta `protobuf:"bytes,2,opt,name=Propuesta,proto3" json:"Propuesta,omitempty"`
	Nchunks              int64      `protobuf:"varint,3,opt,name=Nchunks,proto3" json:"Nchunks,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InfoMaquina) Reset()         { *m = InfoMaquina{} }
func (m *InfoMaquina) String() string { return proto.CompactTextString(m) }
func (*InfoMaquina) ProtoMessage()    {}
func (*InfoMaquina) Descriptor() ([]byte, []int) {
	return fileDescriptor_58dd9776f9ae8f06, []int{1}
}

func (m *InfoMaquina) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoMaquina.Unmarshal(m, b)
}
func (m *InfoMaquina) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoMaquina.Marshal(b, m, deterministic)
}
func (m *InfoMaquina) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoMaquina.Merge(m, src)
}
func (m *InfoMaquina) XXX_Size() int {
	return xxx_messageInfo_InfoMaquina.Size(m)
}
func (m *InfoMaquina) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoMaquina.DiscardUnknown(m)
}

var xxx_messageInfo_InfoMaquina proto.InternalMessageInfo

func (m *InfoMaquina) GetPuerto() string {
	if m != nil {
		return m.Puerto
	}
	return ""
}

func (m *InfoMaquina) GetPropuesta() *Propuesta {
	if m != nil {
		return m.Propuesta
	}
	return nil
}

func (m *InfoMaquina) GetNchunks() int64 {
	if m != nil {
		return m.Nchunks
	}
	return 0
}

func (m *InfoMaquina) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Propuesta)(nil), "Propose.Propuesta")
	proto.RegisterType((*InfoMaquina)(nil), "Propose.InfoMaquina")
}

func init() { proto.RegisterFile("Propose.proto", fileDescriptor_58dd9776f9ae8f06) }

var fileDescriptor_58dd9776f9ae8f06 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x8d, 0x39, 0x7b, 0xf6, 0x3b, 0x44, 0xf9, 0x10, 0x09, 0x4e, 0x47, 0xa7, 0x9b, 0x0e,
	0x2f, 0x01, 0xff, 0xc3, 0x0d, 0x1e, 0x25, 0x82, 0x7b, 0x2c, 0x11, 0x8b, 0x36, 0xa9, 0x69, 0xe3,
	0xe6, 0xe8, 0xff, 0x96, 0xa6, 0x49, 0xe8, 0xe0, 0xf6, 0xbe, 0x4f, 0x20, 0x79, 0xde, 0xc0, 0x55,
	0xed, 0x6c, 0x6f, 0x07, 0xbd, 0xef, 0x9d, 0x1d, 0x2d, 0xae, 0x63, 0xad, 0x7e, 0xa0, 0x9c, 0xa2,
	0xd7, 0xc3, 0xa8, 0xf0, 0x06, 0xe8, 0x4b, 0x77, 0x60, 0x64, 0x4b, 0x76, 0xa5, 0x9c, 0xe2, 0x4c,
	0x38, 0x3b, 0x4f, 0x84, 0xcf, 0x44, 0x30, 0x9a, 0x88, 0x40, 0x84, 0xd5, 0x67, 0xdb, 0x1d, 0xd8,
	0x6a, 0x4b, 0x76, 0x54, 0x86, 0x1c, 0x19, 0x67, 0x17, 0x99, 0xf1, 0xc8, 0x04, 0x2b, 0x32, 0x13,
	0xd5, 0x2f, 0x81, 0xcd, 0xd1, 0xbc, 0xd9, 0x27, 0xf5, 0xe5, 0x5b, 0xa3, 0xf0, 0x0e, 0x8a, 0xda,
	0x6b, 0x37, 0xda, 0x28, 0x11, 0x1b, 0x3e, 0x2c, 0x34, 0x83, 0xcd, 0x86, 0xe3, 0x3e, 0x4d, 0xca,
	0x27, 0x72, 0xb1, 0x85, 0xc1, 0xfa, 0xd4, 0xbc, 0x7b, 0xf3, 0x31, 0x04, 0x57, 0x2a, 0x53, 0x9d,
	0x3c, 0x4e, 0xaa, 0xd3, 0xc1, 0xb7, 0x94, 0x21, 0xf3, 0x23, 0x5c, 0x87, 0xdb, 0x8c, 0x76, 0xcf,
	0xda, 0x7d, 0xb7, 0x8d, 0xc6, 0x47, 0xb8, 0x4c, 0x08, 0x6f, 0xf3, 0x5b, 0x0b, 0xd9, 0xfb, 0x7f,
	0x0c, 0xaa, 0xb3, 0xd7, 0x22, 0xfc, 0xb0, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x12, 0x0b, 0xc7,
	0x3a, 0x72, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProponerServiceClient is the client API for ProponerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProponerServiceClient interface {
	Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error)
}

type proponerServiceClient struct {
	cc *grpc.ClientConn
}

func NewProponerServiceClient(cc *grpc.ClientConn) ProponerServiceClient {
	return &proponerServiceClient{cc}
}

func (c *proponerServiceClient) Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error) {
	out := new(Propuesta)
	err := c.cc.Invoke(ctx, "/Propose.ProponerService/Proponer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProponerServiceServer is the server API for ProponerService service.
type ProponerServiceServer interface {
	Proponer(context.Context, *InfoMaquina) (*Propuesta, error)
}

// UnimplementedProponerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProponerServiceServer struct {
}

func (*UnimplementedProponerServiceServer) Proponer(ctx context.Context, req *InfoMaquina) (*Propuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proponer not implemented")
}

func RegisterProponerServiceServer(s *grpc.Server, srv ProponerServiceServer) {
	s.RegisterService(&_ProponerService_serviceDesc, srv)
}

func _ProponerService_Proponer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoMaquina)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProponerServiceServer).Proponer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Propose.ProponerService/Proponer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProponerServiceServer).Proponer(ctx, req.(*InfoMaquina))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProponerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ProponerService",
	HandlerType: (*ProponerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proponer",
			Handler:    _ProponerService_Proponer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Propose.proto",
}
