// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Uploads.proto

package Uploads

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Part                 int32    `protobuf:"varint,3,opt,name=Part,proto3" json:"Part,omitempty"`
	Puerto               string   `protobuf:"bytes,4,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3639ddf53b3fb5, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chunk) GetPart() int32 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *Chunk) GetPuerto() string {
	if m != nil {
		return m.Puerto
	}
	return ""
}

type UploadStatus struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3639ddf53b3fb5, []int{1}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type InfoChunk struct {
	Port                 string   `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
	Namepart             string   `protobuf:"bytes,2,opt,name=Namepart,proto3" json:"Namepart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoChunk) Reset()         { *m = InfoChunk{} }
func (m *InfoChunk) String() string { return proto.CompactTextString(m) }
func (*InfoChunk) ProtoMessage()    {}
func (*InfoChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3639ddf53b3fb5, []int{2}
}

func (m *InfoChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoChunk.Unmarshal(m, b)
}
func (m *InfoChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoChunk.Marshal(b, m, deterministic)
}
func (m *InfoChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoChunk.Merge(m, src)
}
func (m *InfoChunk) XXX_Size() int {
	return xxx_messageInfo_InfoChunk.Size(m)
}
func (m *InfoChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoChunk.DiscardUnknown(m)
}

var xxx_messageInfo_InfoChunk proto.InternalMessageInfo

func (m *InfoChunk) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *InfoChunk) GetNamepart() string {
	if m != nil {
		return m.Namepart
	}
	return ""
}

type Content struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Nametrozo            string   `protobuf:"bytes,2,opt,name=Nametrozo,proto3" json:"Nametrozo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3639ddf53b3fb5, []int{3}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Content) GetNametrozo() string {
	if m != nil {
		return m.Nametrozo
	}
	return ""
}

func init() {
	proto.RegisterType((*Chunk)(nil), "Uploads.Chunk")
	proto.RegisterType((*UploadStatus)(nil), "Uploads.UploadStatus")
	proto.RegisterType((*InfoChunk)(nil), "Uploads.InfoChunk")
	proto.RegisterType((*Content)(nil), "Uploads.Content")
}

func init() { proto.RegisterFile("Uploads.proto", fileDescriptor_1d3639ddf53b3fb5) }

var fileDescriptor_1d3639ddf53b3fb5 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x35, 0xda, 0x8f, 0xdd, 0xa1, 0xb6, 0x32, 0xa0, 0x2c, 0x8b, 0x87, 0x65, 0x4f, 0x7b, 0x2a,
	0xd2, 0xa2, 0x17, 0x4f, 0x52, 0x45, 0x7b, 0x50, 0x4a, 0xc4, 0x1f, 0x10, 0x35, 0x6a, 0x51, 0x33,
	0x4b, 0x36, 0xab, 0xe0, 0xaf, 0x97, 0x24, 0x9b, 0xb4, 0x27, 0xc1, 0xdb, 0xbc, 0x47, 0xe6, 0x7d,
	0x4c, 0x60, 0xff, 0xa1, 0xfe, 0x20, 0xf1, 0xdc, 0x4c, 0x6b, 0x4d, 0x86, 0x70, 0xd8, 0xc1, 0x52,
	0x40, 0x7f, 0xf1, 0xd6, 0xaa, 0x77, 0xcc, 0x60, 0xb8, 0x20, 0x65, 0xa4, 0x32, 0x19, 0x2b, 0x58,
	0x35, 0xe2, 0x01, 0x22, 0x42, 0xef, 0x4e, 0x7c, 0xca, 0x6c, 0xb7, 0x60, 0x55, 0xca, 0xdd, 0x6c,
	0xb9, 0x95, 0xd0, 0x26, 0xdb, 0x2b, 0x58, 0xd5, 0xe7, 0x6e, 0xc6, 0x23, 0x18, 0xac, 0x5a, 0xa9,
	0x0d, 0x65, 0x3d, 0xf7, 0xb2, 0x43, 0x65, 0x05, 0x23, 0xef, 0x76, 0x6f, 0x84, 0x69, 0x1b, 0xeb,
	0x74, 0x2b, 0x9b, 0x46, 0xbc, 0x4a, 0xe7, 0x94, 0xf2, 0x00, 0xcb, 0x73, 0x48, 0x97, 0xea, 0x85,
	0x7c, 0x20, 0x6b, 0x41, 0xda, 0x74, 0x6f, 0xdc, 0x8c, 0x39, 0x24, 0xd6, 0xbe, 0xb6, 0xd6, 0x3e,
	0x4e, 0xc4, 0xe5, 0x45, 0x2c, 0xf0, 0x47, 0x97, 0x63, 0x48, 0xed, 0x82, 0xd1, 0xf4, 0x43, 0x9d,
	0xc2, 0x86, 0x98, 0x5d, 0xc1, 0xf8, 0xba, 0xf5, 0x51, 0xa5, 0xfe, 0x5a, 0x3f, 0x49, 0x9c, 0xc3,
	0xc0, 0x67, 0xc7, 0xf1, 0x34, 0x5c, 0xd0, 0xc5, 0xcb, 0x0f, 0x23, 0xde, 0x2e, 0x57, 0xee, 0x54,
	0x6c, 0x76, 0x03, 0x13, 0xee, 0x32, 0xad, 0x75, 0xd0, 0x39, 0x85, 0x24, 0x50, 0xff, 0x51, 0x5a,
	0xc2, 0xe4, 0x92, 0xbe, 0xd5, 0x76, 0xa2, 0x33, 0x48, 0x02, 0x85, 0x18, 0x37, 0xe3, 0xd9, 0xf2,
	0x83, 0x8d, 0xba, 0xef, 0x6c, 0x85, 0x4e, 0xd8, 0xe3, 0xc0, 0x7d, 0xfc, 0xfc, 0x37, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0x6d, 0xa8, 0x31, 0x09, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuploadServiceClient is the client API for GuploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuploadServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (GuploadService_UploadClient, error)
}

type guploadServiceClient struct {
	cc *grpc.ClientConn
}

func NewGuploadServiceClient(cc *grpc.ClientConn) GuploadServiceClient {
	return &guploadServiceClient{cc}
}

func (c *guploadServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (GuploadService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GuploadService_serviceDesc.Streams[0], "/Uploads.GuploadService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &guploadServiceUploadClient{stream}
	return x, nil
}

type GuploadService_UploadClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*UploadStatus, error)
	grpc.ClientStream
}

type guploadServiceUploadClient struct {
	grpc.ClientStream
}

func (x *guploadServiceUploadClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *guploadServiceUploadClient) CloseAndRecv() (*UploadStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GuploadServiceServer is the server API for GuploadService service.
type GuploadServiceServer interface {
	Upload(GuploadService_UploadServer) error
}

// UnimplementedGuploadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGuploadServiceServer struct {
}

func (*UnimplementedGuploadServiceServer) Upload(srv GuploadService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterGuploadServiceServer(s *grpc.Server, srv GuploadServiceServer) {
	s.RegisterService(&_GuploadService_serviceDesc, srv)
}

func _GuploadService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuploadServiceServer).Upload(&guploadServiceUploadServer{stream})
}

type GuploadService_UploadServer interface {
	SendAndClose(*UploadStatus) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type guploadServiceUploadServer struct {
	grpc.ServerStream
}

func (x *guploadServiceUploadServer) SendAndClose(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *guploadServiceUploadServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GuploadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Uploads.GuploadService",
	HandlerType: (*GuploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _GuploadService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Uploads.proto",
}

// RepartirServiceClient is the client API for RepartirService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepartirServiceClient interface {
	Repartir(ctx context.Context, opts ...grpc.CallOption) (RepartirService_RepartirClient, error)
}

type repartirServiceClient struct {
	cc *grpc.ClientConn
}

func NewRepartirServiceClient(cc *grpc.ClientConn) RepartirServiceClient {
	return &repartirServiceClient{cc}
}

func (c *repartirServiceClient) Repartir(ctx context.Context, opts ...grpc.CallOption) (RepartirService_RepartirClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RepartirService_serviceDesc.Streams[0], "/Uploads.RepartirService/Repartir", opts...)
	if err != nil {
		return nil, err
	}
	x := &repartirServiceRepartirClient{stream}
	return x, nil
}

type RepartirService_RepartirClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*UploadStatus, error)
	grpc.ClientStream
}

type repartirServiceRepartirClient struct {
	grpc.ClientStream
}

func (x *repartirServiceRepartirClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repartirServiceRepartirClient) CloseAndRecv() (*UploadStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RepartirServiceServer is the server API for RepartirService service.
type RepartirServiceServer interface {
	Repartir(RepartirService_RepartirServer) error
}

// UnimplementedRepartirServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRepartirServiceServer struct {
}

func (*UnimplementedRepartirServiceServer) Repartir(srv RepartirService_RepartirServer) error {
	return status.Errorf(codes.Unimplemented, "method Repartir not implemented")
}

func RegisterRepartirServiceServer(s *grpc.Server, srv RepartirServiceServer) {
	s.RegisterService(&_RepartirService_serviceDesc, srv)
}

func _RepartirService_Repartir_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepartirServiceServer).Repartir(&repartirServiceRepartirServer{stream})
}

type RepartirService_RepartirServer interface {
	SendAndClose(*UploadStatus) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type repartirServiceRepartirServer struct {
	grpc.ServerStream
}

func (x *repartirServiceRepartirServer) SendAndClose(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repartirServiceRepartirServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RepartirService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Uploads.RepartirService",
	HandlerType: (*RepartirServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Repartir",
			Handler:       _RepartirService_Repartir_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Uploads.proto",
}

// DownloadServiceClient is the client API for DownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownloadServiceClient interface {
	Download(ctx context.Context, opts ...grpc.CallOption) (DownloadService_DownloadClient, error)
}

type downloadServiceClient struct {
	cc *grpc.ClientConn
}

func NewDownloadServiceClient(cc *grpc.ClientConn) DownloadServiceClient {
	return &downloadServiceClient{cc}
}

func (c *downloadServiceClient) Download(ctx context.Context, opts ...grpc.CallOption) (DownloadService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DownloadService_serviceDesc.Streams[0], "/Uploads.DownloadService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &downloadServiceDownloadClient{stream}
	return x, nil
}

type DownloadService_DownloadClient interface {
	Send(*InfoChunk) error
	Recv() (*Content, error)
	grpc.ClientStream
}

type downloadServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *downloadServiceDownloadClient) Send(m *InfoChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *downloadServiceDownloadClient) Recv() (*Content, error) {
	m := new(Content)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DownloadServiceServer is the server API for DownloadService service.
type DownloadServiceServer interface {
	Download(DownloadService_DownloadServer) error
}

// UnimplementedDownloadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDownloadServiceServer struct {
}

func (*UnimplementedDownloadServiceServer) Download(srv DownloadService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}

func RegisterDownloadServiceServer(s *grpc.Server, srv DownloadServiceServer) {
	s.RegisterService(&_DownloadService_serviceDesc, srv)
}

func _DownloadService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DownloadServiceServer).Download(&downloadServiceDownloadServer{stream})
}

type DownloadService_DownloadServer interface {
	Send(*Content) error
	Recv() (*InfoChunk, error)
	grpc.ServerStream
}

type downloadServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *downloadServiceDownloadServer) Send(m *Content) error {
	return x.ServerStream.SendMsg(m)
}

func (x *downloadServiceDownloadServer) Recv() (*InfoChunk, error) {
	m := new(InfoChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DownloadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Uploads.DownloadService",
	HandlerType: (*DownloadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _DownloadService_Download_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Uploads.proto",
}
