// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: Propose.proto

package Propose

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vm1   string `protobuf:"bytes,1,opt,name=Vm1,proto3" json:"Vm1,omitempty"`
	Vm2   string `protobuf:"bytes,2,opt,name=Vm2,proto3" json:"Vm2,omitempty"`
	Vm3   string `protobuf:"bytes,3,opt,name=Vm3,proto3" json:"Vm3,omitempty"`
	Cant1 int64  `protobuf:"varint,4,opt,name=Cant1,proto3" json:"Cant1,omitempty"`
	Cant2 int64  `protobuf:"varint,5,opt,name=Cant2,proto3" json:"Cant2,omitempty"`
	Cant3 int64  `protobuf:"varint,6,opt,name=Cant3,proto3" json:"Cant3,omitempty"`
}

func (x *Propuesta) Reset() {
	*x = Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta) ProtoMessage() {}

func (x *Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta.ProtoReflect.Descriptor instead.
func (*Propuesta) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{0}
}

func (x *Propuesta) GetVm1() string {
	if x != nil {
		return x.Vm1
	}
	return ""
}

func (x *Propuesta) GetVm2() string {
	if x != nil {
		return x.Vm2
	}
	return ""
}

func (x *Propuesta) GetVm3() string {
	if x != nil {
		return x.Vm3
	}
	return ""
}

func (x *Propuesta) GetCant1() int64 {
	if x != nil {
		return x.Cant1
	}
	return 0
}

func (x *Propuesta) GetCant2() int64 {
	if x != nil {
		return x.Cant2
	}
	return 0
}

func (x *Propuesta) GetCant3() int64 {
	if x != nil {
		return x.Cant3
	}
	return 0
}

type InfoMaquina struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puerto    string     `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	Propuesta *Propuesta `protobuf:"bytes,2,opt,name=Propuesta,proto3" json:"Propuesta,omitempty"`
	Nchunks   int64      `protobuf:"varint,3,opt,name=Nchunks,proto3" json:"Nchunks,omitempty"`
	Name      string     `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *InfoMaquina) Reset() {
	*x = InfoMaquina{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoMaquina) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoMaquina) ProtoMessage() {}

func (x *InfoMaquina) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoMaquina.ProtoReflect.Descriptor instead.
func (*InfoMaquina) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{1}
}

func (x *InfoMaquina) GetPuerto() string {
	if x != nil {
		return x.Puerto
	}
	return ""
}

func (x *InfoMaquina) GetPropuesta() *Propuesta {
	if x != nil {
		return x.Propuesta
	}
	return nil
}

func (x *InfoMaquina) GetNchunks() int64 {
	if x != nil {
		return x.Nchunks
	}
	return 0
}

func (x *InfoMaquina) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Libro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Libro) Reset() {
	*x = Libro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Libro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Libro) ProtoMessage() {}

func (x *Libro) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Libro.ProtoReflect.Descriptor instead.
func (*Libro) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{2}
}

func (x *Libro) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReceptStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ReceptStatus) Reset() {
	*x = ReceptStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceptStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceptStatus) ProtoMessage() {}

func (x *ReceptStatus) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceptStatus.ProtoReflect.Descriptor instead.
func (*ReceptStatus) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{3}
}

func (x *ReceptStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InfoChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puerto string `protobuf:"bytes,1,opt,name=Puerto,proto3" json:"Puerto,omitempty"`
	Part   string `protobuf:"bytes,2,opt,name=Part,proto3" json:"Part,omitempty"`
}

func (x *InfoChunk) Reset() {
	*x = InfoChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Propose_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoChunk) ProtoMessage() {}

func (x *InfoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_Propose_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoChunk.ProtoReflect.Descriptor instead.
func (*InfoChunk) Descriptor() ([]byte, []int) {
	return file_Propose_proto_rawDescGZIP(), []int{4}
}

func (x *InfoChunk) GetPuerto() string {
	if x != nil {
		return x.Puerto
	}
	return ""
}

func (x *InfoChunk) GetPart() string {
	if x != nil {
		return x.Part
	}
	return ""
}

var File_Propose_proto protoreflect.FileDescriptor

var file_Propose_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x6d, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x6d, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x6d, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x6d, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x6d,
	0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x6d, 0x33, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x61, 0x6e, 0x74, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x61, 0x6e,
	0x74, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x6e, 0x74, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x43, 0x61, 0x6e, 0x74, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x6e, 0x74,
	0x33, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x61, 0x6e, 0x74, 0x33, 0x22, 0x85,
	0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x71, 0x75, 0x69, 0x6e, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x50, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x09, 0x50,
	0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4e, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x70, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a,
	0x09, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75,
	0x65, 0x72, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x65, 0x72,
	0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x50, 0x61, 0x72, 0x74, 0x32, 0x49, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x6e,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x71, 0x75, 0x69, 0x6e, 0x61, 0x1a, 0x12, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22,
	0x00, 0x32, 0x44, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x12, 0x15, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x70, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69,
	0x62, 0x72, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x32, 0x4d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x61,
	0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x0e,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x1a, 0x12,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Propose_proto_rawDescOnce sync.Once
	file_Propose_proto_rawDescData = file_Propose_proto_rawDesc
)

func file_Propose_proto_rawDescGZIP() []byte {
	file_Propose_proto_rawDescOnce.Do(func() {
		file_Propose_proto_rawDescData = protoimpl.X.CompressGZIP(file_Propose_proto_rawDescData)
	})
	return file_Propose_proto_rawDescData
}

var file_Propose_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Propose_proto_goTypes = []interface{}{
	(*Propuesta)(nil),    // 0: Propose.Propuesta
	(*InfoMaquina)(nil),  // 1: Propose.InfoMaquina
	(*Libro)(nil),        // 2: Propose.Libro
	(*ReceptStatus)(nil), // 3: Propose.ReceptStatus
	(*InfoChunk)(nil),    // 4: Propose.InfoChunk
}
var file_Propose_proto_depIdxs = []int32{
	0, // 0: Propose.InfoMaquina.Propuesta:type_name -> Propose.Propuesta
	1, // 1: Propose.ProponerService.Proponer:input_type -> Propose.InfoMaquina
	3, // 2: Propose.ListarService.Listar:input_type -> Propose.ReceptStatus
	2, // 3: Propose.ListarChunksService.ListarChunks:input_type -> Propose.Libro
	0, // 4: Propose.ProponerService.Proponer:output_type -> Propose.Propuesta
	2, // 5: Propose.ListarService.Listar:output_type -> Propose.Libro
	4, // 6: Propose.ListarChunksService.ListarChunks:output_type -> Propose.InfoChunk
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Propose_proto_init() }
func file_Propose_proto_init() {
	if File_Propose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Propose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Propose_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoMaquina); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Propose_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Libro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Propose_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceptStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Propose_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Propose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_Propose_proto_goTypes,
		DependencyIndexes: file_Propose_proto_depIdxs,
		MessageInfos:      file_Propose_proto_msgTypes,
	}.Build()
	File_Propose_proto = out.File
	file_Propose_proto_rawDesc = nil
	file_Propose_proto_goTypes = nil
	file_Propose_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProponerServiceClient is the client API for ProponerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProponerServiceClient interface {
	Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error)
}

type proponerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProponerServiceClient(cc grpc.ClientConnInterface) ProponerServiceClient {
	return &proponerServiceClient{cc}
}

func (c *proponerServiceClient) Proponer(ctx context.Context, in *InfoMaquina, opts ...grpc.CallOption) (*Propuesta, error) {
	out := new(Propuesta)
	err := c.cc.Invoke(ctx, "/Propose.ProponerService/Proponer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProponerServiceServer is the server API for ProponerService service.
type ProponerServiceServer interface {
	Proponer(context.Context, *InfoMaquina) (*Propuesta, error)
}

// UnimplementedProponerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProponerServiceServer struct {
}

func (*UnimplementedProponerServiceServer) Proponer(context.Context, *InfoMaquina) (*Propuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proponer not implemented")
}

func RegisterProponerServiceServer(s *grpc.Server, srv ProponerServiceServer) {
	s.RegisterService(&_ProponerService_serviceDesc, srv)
}

func _ProponerService_Proponer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoMaquina)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProponerServiceServer).Proponer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Propose.ProponerService/Proponer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProponerServiceServer).Proponer(ctx, req.(*InfoMaquina))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProponerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ProponerService",
	HandlerType: (*ProponerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proponer",
			Handler:    _ProponerService_Proponer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Propose.proto",
}

// ListarServiceClient is the client API for ListarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListarServiceClient interface {
	Listar(ctx context.Context, in *ReceptStatus, opts ...grpc.CallOption) (ListarService_ListarClient, error)
}

type listarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListarServiceClient(cc grpc.ClientConnInterface) ListarServiceClient {
	return &listarServiceClient{cc}
}

func (c *listarServiceClient) Listar(ctx context.Context, in *ReceptStatus, opts ...grpc.CallOption) (ListarService_ListarClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListarService_serviceDesc.Streams[0], "/Propose.ListarService/Listar", opts...)
	if err != nil {
		return nil, err
	}
	x := &listarServiceListarClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ListarService_ListarClient interface {
	Recv() (*Libro, error)
	grpc.ClientStream
}

type listarServiceListarClient struct {
	grpc.ClientStream
}

func (x *listarServiceListarClient) Recv() (*Libro, error) {
	m := new(Libro)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ListarServiceServer is the server API for ListarService service.
type ListarServiceServer interface {
	Listar(*ReceptStatus, ListarService_ListarServer) error
}

// UnimplementedListarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListarServiceServer struct {
}

func (*UnimplementedListarServiceServer) Listar(*ReceptStatus, ListarService_ListarServer) error {
	return status.Errorf(codes.Unimplemented, "method Listar not implemented")
}

func RegisterListarServiceServer(s *grpc.Server, srv ListarServiceServer) {
	s.RegisterService(&_ListarService_serviceDesc, srv)
}

func _ListarService_Listar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceptStatus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListarServiceServer).Listar(m, &listarServiceListarServer{stream})
}

type ListarService_ListarServer interface {
	Send(*Libro) error
	grpc.ServerStream
}

type listarServiceListarServer struct {
	grpc.ServerStream
}

func (x *listarServiceListarServer) Send(m *Libro) error {
	return x.ServerStream.SendMsg(m)
}

var _ListarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ListarService",
	HandlerType: (*ListarServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listar",
			Handler:       _ListarService_Listar_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Propose.proto",
}

// ListarChunksServiceClient is the client API for ListarChunksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListarChunksServiceClient interface {
	ListarChunks(ctx context.Context, in *Libro, opts ...grpc.CallOption) (ListarChunksService_ListarChunksClient, error)
}

type listarChunksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListarChunksServiceClient(cc grpc.ClientConnInterface) ListarChunksServiceClient {
	return &listarChunksServiceClient{cc}
}

func (c *listarChunksServiceClient) ListarChunks(ctx context.Context, in *Libro, opts ...grpc.CallOption) (ListarChunksService_ListarChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListarChunksService_serviceDesc.Streams[0], "/Propose.ListarChunksService/ListarChunks", opts...)
	if err != nil {
		return nil, err
	}
	x := &listarChunksServiceListarChunksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ListarChunksService_ListarChunksClient interface {
	Recv() (*InfoChunk, error)
	grpc.ClientStream
}

type listarChunksServiceListarChunksClient struct {
	grpc.ClientStream
}

func (x *listarChunksServiceListarChunksClient) Recv() (*InfoChunk, error) {
	m := new(InfoChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ListarChunksServiceServer is the server API for ListarChunksService service.
type ListarChunksServiceServer interface {
	ListarChunks(*Libro, ListarChunksService_ListarChunksServer) error
}

// UnimplementedListarChunksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListarChunksServiceServer struct {
}

func (*UnimplementedListarChunksServiceServer) ListarChunks(*Libro, ListarChunksService_ListarChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListarChunks not implemented")
}

func RegisterListarChunksServiceServer(s *grpc.Server, srv ListarChunksServiceServer) {
	s.RegisterService(&_ListarChunksService_serviceDesc, srv)
}

func _ListarChunksService_ListarChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Libro)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListarChunksServiceServer).ListarChunks(m, &listarChunksServiceListarChunksServer{stream})
}

type ListarChunksService_ListarChunksServer interface {
	Send(*InfoChunk) error
	grpc.ServerStream
}

type listarChunksServiceListarChunksServer struct {
	grpc.ServerStream
}

func (x *listarChunksServiceListarChunksServer) Send(m *InfoChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _ListarChunksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Propose.ListarChunksService",
	HandlerType: (*ListarChunksServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListarChunks",
			Handler:       _ListarChunksService_ListarChunks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Propose.proto",
}
